/* fun.js version 3.0 */
function g(x){return document.getElementById(x);}
function t(x){return document.getElementsByTagName(x);}
function c(x){return document.getElementsByClassName(x);}
function int(str){return parseInt(str);}
String.prototype.span = function(start,end,str=this){return str.substring(start,end+1);};
function span(start,end,str){return str.substring(start,end+1);}
function getPartFrom(a,str){return str.span(a+1,str.length-1);}
function tt(num){return num.toString().padStart(2,"0");}
function nopx(str){return int(str.span(0,str.length-2));}
function cleanURL(str=""){if(str.charAt(str.length-1)==='/') str=str.span(0,str.length-2);if(str.span(0,7)==="https://")return str.span(8,str.length-1);if(str.span(0,6)==="http://")return str.span(7,str.length-1);return str;}
function replaceWhitespace(str,replacer=""){const m=replaceChar(' ',replacer,str);return replaceChar('\n',replacer,m);}
function replaceChar(valA,valB,str){let ret=str.replace(valA,valB);while(ret.indexOf(valA)>=0)ret=ret.replace(valA,valB);return ret;} 
function simpleHash(plain){let h=0;for(let i=0;i<plain.length;i++){char=plain.charCodeAt(i);h=((h<<5)-h)+char;h=h&h;}return h;}
function getGdNow(){const today=new Date();return today.getFullYear().toString().padStart(4,"0")+tt(today.getMonth()+1)+tt(today.getDate())+tt(today.getHours())+tt(today.getMinutes())+tt(today.getSeconds())+today.getMilliseconds().toString().padStart(3,"0");}
function gdToJd(gd){const Y=parseInt(gd.substring(0,4));const M=parseInt(gd.substring(4,6));const D=parseInt(gd.substring(6,8));const a=parseInt((14-M)/12);const y=Y+4800-a;let m=M+12*a-3;return D+parseInt((153*m+2)/5)+365*y+parseInt(y/4)-parseInt(y/100)+parseInt(y/400)-32045;}
function jdToGd(jd){const Q=parseInt(jd)+0.5;const Z=parseInt(Q);const W=parseInt((Z-1867216.25)/36524.25);const B=parseInt(Z+1+W-W/4+1524);const C=parseInt((B-122.1)/365.25);const D=parseInt(365.25*C);const E=parseInt((B-D)/30.6001);const F=parseInt(30.6001*E);const day=parseInt(B-D-F+(Q-Z));const month=parseInt((E-1<13&&E-1>-1)?E-1:E-13);const year=parseInt((month<=2)?C-4715:C-4716);return year.toString().padStart(4,"0")+tt(month)+tt(day);}
function gdToGdtime(gd){return gd.toString().substring(8,17);}
function gdtimeToTime1(gdtime){const d=gdtime.toString();let ret=d.substring(0,2);const x=d.length;if(x>2)ret+=":"+d.substring(2,4);if(x>4)ret+=":"+d.substring(4,6);if(x>6)ret+=":"+d.substring(6,9);return ret;}
function gdToFullFormat1(gd){const d=gd.toString();if(d.length<17){console.warn('gdToFullFormat1() input is shorter than expected');}return "["+d.substring(0,4)+"-"+d.substring(4,6)+"-"+d.substring(6,8)+" "+d.substring(8,10)+":"+d.substring(10,12)+":"+d.substring(12,14)+":"+d.substring(14,17)+"]";}
function gdToDateFormat1(gd){var month=monthName(span(4,5,gd));return parseInt(span(6,7,gd))+" "+month+" "+span(0,3,gd);}
function monthIndex(month){const m=month.toString().substring(0,3).toLowerCase();switch(m){case'jan':return 1;case'feb':return 2;case'mar':return 3;case'apr':return 4;case'may':return 5;case'jun':return 6;case'jul':return 7;case'aug':return 8;case'sep':return 9;case'oct':return 10;case'nov':return 11;case'dec':return 12;default:return -1;}}
function monthName(index){const i=parseInt(index);switch(i){case 1:return 'January';case 2:return 'February';case 3:return 'March';case 4:return 'April';case 5:return 'May';case 6:return 'June';case 7:return 'July';case 8:return 'August';case 9:return 'September';case 10:return 'October';case 11:return 'November';case 12:return 'December';default:return '[monthName() invalid index]';}}
function weekdayIndex(gd){const jd=gdToJd(gd);return parseInt(jd)%7;}
function weekdayName(index){const i=parseInt(index);switch(i){case 0:return 'Monday';case 1:return 'Tuesday';case 2:return 'Wednesday';case 3:return 'Thursday';case 4:return 'Friday';case 5:return 'Saturday';case 6:return 'Sunday';default:return '[weekdayName() invalid index]';}}
function daysDiff(gdfrom,gdto){return parseInt(gdToJd(gdto))-parseInt(gdToJd(gdfrom));}
function dateDiff(gdfrom,gdto){const daysFloored=parseInt(gdToJd(gdto))-parseInt(gdToJd(gdfrom));const h1=int(gdfrom.substring(8,10));const h2=int(gdto.substring(8,10));const m1=int(gdto.substring(10,12));const m2=int(gdto.substring(10,12));const dayfloat1=(h1+m1/60)/24;const dayfloat2=(h2+m2/60)/24;let daymins=(dayfloat2-dayfloat1);return {daysFloat:daysFloored+daymins,daysInt:daysFloored};}
function timeNow(){var today=new Date();return today.getHours()+":"+tt(today.getMinutes())+":"+tt(today.getSeconds());}
function getTime(){var today=new Date();return "["+tt(today.getFullYear())+"-"+tt(today.getMonth()+1)+"-"+tt(today.getDate())+" "+tt(today.getHours())+":"+tt(today.getMinutes())+":"+tt(today.getSeconds())+"]";}
function gdNow(){var today=new Date();return tt(today.getFullYear())+tt(today.getMonth()+1)+tt(today.getDate())+tt(today.getHours())+tt(today.getMinutes());}
function dateNow(){var today=new Date();var dd=String(today.getDate()).padStart(2,'0');var mm=String(today.getMonth()+1).padStart(2,'0');/*January is 0!*/var yyyy=today.getFullYear();return yyyy.toString()+mm.toString()+dd.toString();}
function getExactTime(){const d=new Date();return tt(d.getHours()) + tt(d.getMinutes()) + tt(d.getSeconds()) + tt(d.getMilliseconds());}
function gd(jd){var Q=jd+0.5;var Z=Math.floor(Q);var W=Math.floor((Z-1867216.25)/36524.25);var B=Math.floor(Z+1+W-W/4+1524);var C=Math.floor((B-122.1)/365.25);var D=Math.floor(365.25*C);var E=Math.floor((B-D)/30.6001);var F=Math.floor(30.6001*E);var day=Math.floor(B-D-F+(Q-Z));var month=Math.floor((E-1<13&&E-1>-1)?E-1:E-13);var year=Math.floor((month<=2)?C-4715:C-4716);return year.toString()+''+tt(month)+tt(day);}
function jd(gd){var Y=Math.floor(gd/10000);var M=Math.floor((gd/100)%100);var D=Math.floor(gd%100);a=Math.floor((14-M)/12);y=Y+4800-a;let m=M+12*a-3;return D+Math.floor((153*m+2)/5)+365*y+Math.floor(y/4)-Math.floor(y/100)+Math.floor(y/400)-32045;}
function reformTime(str){return int(span(9,10,str))+"/"+int(span(6,7,str))+"/"+span(3,4,str)+" "+span(12,13,str)+":"+span(15,16,str);}
function reformTimeStrict(str){return span(9,10,str)+"/"+span(6,7,str)+"/"+span(3,4,str)+" "+span(12,13,str)+":"+span(15,16,str);}
function dayIndex(jd){return Math.floor(jd)%7;}
function day(jd){switch(Math.floor(jd)%7){case 0:return"Mon";break;case 1:return"Tue";break;case 2:return"Wed";break;case 3:return"Thu";break;case 4:return"Fri";break;case 5:return"Sat";break;case 6:return"Sun";break;default:return"Unknown";}}
function dayToWeekIndex(day='mon'){const d=day.toLowerCase();if(d==="mon")return 0;if(d==="tue")return 1;if(d==="wed")return 2;if(d==="thu")return 3;if(d==="fri")return 4;if(d==="sat")return 5;if(d==="sun")return 6;return -1;}
function nameMonth(gd){switch(span(4,5,gd)){case'01':return"January";break;case'02':return"February";break;case'03':return"March";break;case'04':return"April";break;case'05':return"May";break;case'06':return"June";break;case'07':return"July";break;case'08':return"August";break;case'09':return"September";break;case'10':return"October";break;case'11':return"November";break;case'12':return"December";break;default:return"Mistake";}}
function dateFormat(gd){var month;switch(span(4,5,gd)){case'01':month="Jan";break;case'02':month="Feb";break;case'03':month="Mar";break;case'04':month="Apr";break;case'05':month="May";break;case'06':month="Jun";break;case'07':month="Jul";break;case'08':month="Aug";break;case'09':month="Sep";break;case'10':month="Oct";break;case'11':month="Nov";break;case'12':month="Dec";break;default:month="Mistake";}return Math.floor(span(6,7,gd))+" "+month+" "+span(0,3,gd);}
function dateFormatToGD(f="1 Jan 1789"){const v=f.splitToArray(' ');let monthID="00";switch(v[1]){case'Jan':monthID='01';break;case'Feb':monthID='02';break;case'Mar':monthID='03';break;case'Apr':monthID='04';break;case'May':monthID='05';break;case'Jun':monthID='06';break;case'Jul':monthID='07';break;case'Aug':monthID='08';break;case'Sep':monthID='09';break;case'Oct':monthID='10';break;case'Nov':monthID='11';break;case'Dec':monthID='12';break;default:break;}return v[2]+monthID+tt(v[0]);}
function dateFormatToShort(f="Mon Sep 02 2000"){let monthID="0";switch(span(4,6,f)){case'Jan':monthID='01';break;case'Feb':monthID='02';break;case'Mar':monthID='03';break;case'Apr':monthID='04';break;case'May':monthID='05';break;case'Jun':monthID='06';break;case'Jul':monthID='07';break;case'Aug':monthID='08';break;case'Sep':monthID='09';break;case'Oct':monthID='10';break;case'Nov':monthID='11';break;case'Dec':monthID='12';break;default:break;}return int(span(8,9,f))+"/"+int(monthID)+"/"+span(13,14,f);}
function dateDifference(gdfrom,gdto){var daysDiff=parseInt(jd(span(0,7,gdto)))-parseInt(jd(span(0,7,gdfrom)));var mfrom=parseInt(span(8,9,gdfrom))*60+parseInt(span(10,11,gdfrom));var mto=parseInt(span(8,9,gdto))*60+parseInt(span(10,11,gdto));var timeDiff=mto-mfrom;if(timeDiff<0){timeDiff=24*60+timeDiff;--daysDiff;}return daysDiff+"d "+Math.floor(timeDiff/60)+"h "+timeDiff%60+"m";}
function dateDifferenceFull(gdfrom,gdto){var daysDiff = int(jd(span(0,7,gdto))) - int(jd(span(0,7,gdfrom)));var mfrom = int(span(8,9,gdfrom))*60 + int(span(10,11,gdfrom));var mto = int(span(8,9,gdto))*60 + int(span(10,11,gdto));var timeDiff = mto - mfrom;	if(timeDiff<0){	timeDiff=24*60+timeDiff;--daysDiff;}let ret = "";	const years = int(daysDiff/365);	if (years > 0) {		ret += years;		if (years > 1) ret += " years ";		else ret += " year ";	}	if (daysDiff%365 > 0) {		ret += daysDiff%365;		if (daysDiff%365 > 1) ret += " days ";		else ret += " day ";	}	if (int(timeDiff/60) > 0) {		ret += int(timeDiff/60);		if (int(timeDiff/60) > 1) ret += " hours ";		else ret += " hour ";	}	if (timeDiff%60 > 0) {		ret += timeDiff%60;		if (timeDiff%60 > 1) ret += " minutes";		else ret += " minute";	}	else ret += 'now';	return ret;}
function dayOfMonthInt(jd){var Q=jd+0.5;var Z=Math.floor(Q);var W=Math.floor((Z-1867216.25)/36524.25);var B=Math.floor(Z+1+W-W/4+1524);var C=Math.floor((B-122.1)/365.25);var D=Math.floor(365.25*C);var E=Math.floor((B-D)/30.6001);var F=Math.floor(30.6001*E);return Math.floor(B-D-F+(Q-Z));}
function daysOfMonth(jdd1st){var currMonth=span(4,5,gd(jdd1st));jdd1st+=30;var i=0;while(i<5){if(span(4,5,gd(jdd1st))===currMonth)return 31-i;else{++i;--jdd1st;}}return 30;}
function refreshPage(){window.location.reload();}
function clipboard(t){cpyToClip(t);}
function cpyToClip(t){if(navigator.clipboard && window.isSecureContext)return navigator.clipboard.writeText(t);else{let a=document.createElement("textarea");a.value=t;a.style.position="fixed";a.style.left="-999999px";a.style.top="-999999px";document.body.appendChild(a);a.focus();a.select();return new Promise((res, rej) => {document.execCommand('copy') ? res() : rej();textArea.remove();});}}
function redir(w){window.location.replace(w);}
function fadeIn(el,parent=document.body,duration_ms=300){el.style.cssText+="visibility:hidden;opacity:0";parent.appendChild(el);setTimeout(function(){el.style.cssText+="transition:visibility "+(duration_ms/1000)+"s, opacity "+(duration_ms/1000)+"s;visibility:visible;opacity:1";},10);}
function fadeOut(el,duration_ms=700){el.style.cssText += "transition:visibility "+(duration_ms/1000)+"s, opacity "+(duration_ms/1000)+"s;visibility:hidden;opacity:0";setTimeout(function(){el.remove();},duration_ms);}
function purgeTag(tag){const x = t(tag);const len = x.length;for(let d=0; d<len; ++d){x[0].remove();}}
function hideTag(tag){const x = t(tag);const len = x.length;for(let d of x) d.style.display="none";}
function hideClass(cl){const x = c(cl);const len = x.length;for(let d of x) d.style.display="none";}
function btnLoading(element,duration=1500){const prev = element.innerHTML;element.innerHTML = "loading...";let interval123 = setInterval(function(){element.innerHTML = prev;clearInterval(interval123);},duration);}
function windowPopup(content=document.createElement('div'),window_title="untitled",window_style="",topbar_style="",buttons_style=""){if(content.innerHTML==="")content.innerHTML="no content";const w=document.createElement('div');const w_minimized=document.createElement('div');const idis2="window2"+randHexColor().span(1,6);w_minimized.id=idis2;const idis="window"+randHexColor().span(1,6);w.id=idis;const style_window_position_n_dimensions="display:inline-block;position:fixed;top:7%;left:7%;width:90%;max-width:600px;min-height:300px;max-height:80vh;";const style_window_border="border:solid;border-width:1px 3px 3px 1px;border-color:#3F4141;";const style_topbar_colors="background-color:#3F4141;";const style_buttons="cursor:pointer;border:none;width:17px;margin:0px 2px;height:17px;border-radius:10px;"+buttons_style;w.style.cssText="background-color:black;"+style_window_position_n_dimensions+style_window_border+window_style;const b=document.createElement('div');const onc1="g('"+idis+"').style.cssText+='width:100%;height:100%;max-width:10000px;top:0px;left:0px;';";const onc2="g('"+idis+"').style.display='none';"+"g('"+idis2+"').style.display='inline-block';";const onc3="g('"+idis+"').remove()";b.style.cssText="cursor:grab;width:100%;padding:0px;height:30px;text-align:center;"+style_topbar_colors;b.innerHTML="<label style='padding-top:5px;display:inline-block;'>"+window_title+"</label><label style='float:right;display:inline-block;'><button style='"+style_buttons+"background-color:green;'title='fullscreen/smaller view'onclick="+onc1+"></button><button style='"+style_buttons+"background-color:orange;'title='minimize'onclick="+onc2+"></button><button style='"+style_buttons+"background-color:red;'title='close'onclick="+onc3+"></button></label>";w.appendChild(b);w.appendChild(content);w_minimized.style.cssText="position:fixed;bottom:0px;left:10px;padding-top:5px;text-align:center;display:none;width:200px;height:30px;border:solid;border-width:1px 1px 0px 1px;border-radius:2px 2px 0px 0px;background-color:#3F4141;cursor:pointer;";w_minimized.innerHTML=window_title;w_minimized.onclick=function(){this.style.display="none";w.style.display="inline-block";};document.body.appendChild(w);document.body.appendChild(w_minimized);}
function openInFullscreen(el,extra_style={bg:"",topbar:"",btn:""}){const tmp={parent:el.parentElement,width:el.style.width};el.style.width="100%";const f=document.createElement('div');f.style.cssText="z-index:5;position:fixed;top:0px;left:0px;width:100%;height:100vh;background-color:#121212;background-opacity:0.3;"+extra_style.bg;const t=document.createElement('div');t.style.cssText="width:100%;height:50px;background-color:#232323;"+extra_style.topbar;const b=document.createElement('button');b.style.cssText="font-family:monospace;padding:5px;position:fixed;top:0px;right:0px;font-weight:bold;display:inline-block;width:50px;border:none;color:#dedede;height:50px;background-color:#121212;background-color:transparent;cursor:pointer;"+extra_style.btn;b.onclick=function(){el.style.width=tmp.width;tmp.parent.appendChild(el);fadeOut(this.parentElement.parentElement,0.3);};b.title="close";b.innerHTML="X";t.appendChild(b);f.appendChild(t);f.appendChild(el);document.body.appendChild(f);}
function popWindow(inner,title="untitled"){const bg=document.createElement('div');const pop=document.createElement('div');const ti=document.createElement('div');const inn=document.createElement('div');const ok_btn=document.createElement('button');bg.style.cssText="font-family:'San Francisco',Roboto;font-size:0.9em;padding-top:50px;position:fixed;top:0px;left:0px;width:100%;height:100vh;background-color:rgba(0,0,0,0.8);text-align:center;";pop.style.cssText="display:inline-block;font-family:inherit;border-radius:13px;background-color:#f9f9f9;color:#090909;max-width:96%;max-height:80%;margin:auto;padding:10px 0px 0px 0px;text-align:center;";ti.style.cssText="font-family:inherit;font-size:1.15em;background-color:transparent;color:#020202;width:100%;font-weight:bold;text-align:center;padding:5px;margin:0px;";inn.style.cssText="text-align:left;font-family:inherit;background-color:transparent;min-height:100px;color:#090909;max-width:100%;margin:0px;margin:auto;padding:10px 10px;px;overflow-y:auto;";inn.style.maxHeight=(window.innerHeight*0.8-200)+'px';ok_btn.style.cssText="font-family:inherit;font-weight:bold;cursor:pointer;background-color:transparent;color:#0d78e5;width:100%;margin:0px;padding:7px 0px;border:solid #ababab;border-width:1px 0px 0px 0px;text-align:center;";inn.innerHTML=inner;ti.innerHTML=title;ok_btn.innerHTML="OK";ok_btn.onclick=function(){fadeOut(bg,300);};bg.appendChild(pop);pop.appendChild(ti);pop.appendChild(inn);pop.appendChild(ok_btn);fadeIn(bg,document.body,100);}
function dynSort(p) {var so=1;if(p[0]==="-"){so=-1;p=p.substr(1);}return function(a,b){var result=(a[p]<b[p])?-1:(a[p]>b[p])?1:0;return result*so;}}
function existInArr(x,arr){for(let i of arr) if(i === x) return true;return false;}
function arraySum(arr){let sum=0;for(i of arr)sum += i;return sum;}
function arrayAverage(arr){return arraySum(arr)/arr.length;}
function arrayNormalize(arr){const len=arr.length;if(len < 1) return [];let max=arr[0];for(let i of arr) if(i>max) max=i;for(let i=0; i<len; ++i) arr[i]=arr[i]/max;return arr;}
function randFromArr(arr){return arr[int(Math.random()*arr.length)];}
function mergeArr(arr1,arr2){let r=[];for(let i of arr1)r.push(i);for(let i of arr2)r.push(i);return r;}Array.prototype.max = function(){return Math.max.apply(null,this);};
function cpArr(src,dst){if(src===undefined||dst===undefined){console.warn('cpArr error: input array undefined');return;}for(const i of src)dst.push(i);}Array.prototype.rmdup = function(sorted=false){if(this.length===0)return;const r=[];cpArr(this,r);if(!sorted)r.sort();const r2=[];r2.push(r[0]);for(let i=1;i<r.length;++i){if(r[i]!==r[i-1])r2.push(r[i]);}return r2;};
function indexIn(word,str){return str.indexOf(word);}String.prototype.splitToArray = function(c,str=this){let arr = str.split(c);let ret = [];for (let i of arr){if (i != "") ret.push(i);}return ret;};
function splitStr(c,str){let i = 0;const len = str.length;while (i < len){if(str.charAt(i) === c){return [span(0,i-1,str), span(i+1,len-1,str)];}++i;}return [str,""];}
function splitAtString(string,input){const x=input.indexOf(string);return [input.span(0,x-1), input.span(x+string.length,input.length-1)];}
function randHexColor(){const hextable=["0","1","2","3","4","5","6","7","8","9","a","b","c","d","e","f"];let hex="#";for(let i=0;i<6;++i)hex+=hextable[parseInt(Math.random()*15)];return hex;}
function autoPopup(text,duration_ms=3000,addLoadBar=true,extra_style=""){let y=0;let lb=0;for(const i of document.getElementsByTagName('popupnotif9835146')){const r=i.getBoundingClientRect();if(r.top>lb+300)break;y=lb=r.bottom;}if(y>window.innerHeight-300)y=0;const p=document.createElement("popupnotif9835146");p.innerHTML=text;p.style.cssText="position:fixed;top:"+(10+y)+"px;right:10px;max-width:250px;padding:10px;background-color:#343434;font-weight:bold;color:#ababab;"+extra_style;if(addLoadBar){const lb = document.createElement("div");lb.style.cssText="transition: width "+(duration_ms/1000).toFixed(1)+"s linear;position: absolute;bottom: 0;left:0;width:100%;height:3px;background-color:#2279e3;";p.appendChild(lb);setTimeout(function(){lb.style.width="0px";},10);}fadeIn(p,document.body);setTimeout(function(){fadeOut(p);},duration_ms);}
function parseFloat2(t){if(t === undefined || t === null || t === "" || isNaN(t)) return 0.0;return parseFloat(t);}
function parseInt2(t){return parseInt(parseFloat2(t));}

